### ISSUE TITLE
The server got an error at startup

### ISSUE THREAD

**Issue by MrShellad** [lunarbunten/enderscape#20]
[23:36:03] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'enderscape'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.bunten.enderscape.world.EnderscapeBiomes.getSkyBiomeHeight(EnderscapeBiomes.java:56) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.placed.FeaturesClass.<clinit>(FeaturesClass.java:24) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.biomes.CelestialIslandsBiome.getBCLBiome(CelestialIslandsBiome.java:50) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.EnderscapeBiomes.register(EnderscapeBiomes.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.EnderscapeBiomes.<clinit>(EnderscapeBiomes.java:63) ~[enderscape-0.4.0-1.19.2.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at com.google.common.reflect.Reflection.initialize(Reflection.java:66) ~[guava-31.0.1-jre.jar:?]
	at net.bunten.enderscape.Enderscape.onInitialize(Enderscape.java:38) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.bunten.enderscape.config.configs.DebugConfig in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.bunten.enderscape.config.Config.<clinit>(Config.java:23) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.EnderscapeBiomes.getSkyBiomeHeight(EnderscapeBiomes.java:56) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.placed.FeaturesClass.<clinit>(FeaturesClass.java:24) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.biomes.CelestialIslandsBiome.getBCLBiome(CelestialIslandsBiome.java:50) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.EnderscapeBiomes.register(EnderscapeBiomes.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.bunten.enderscape.world.EnderscapeBiomes.<clinit>(EnderscapeBiomes.java:63) ~[enderscape-0.4.0-1.19.2.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at com.google.common.reflect.Reflection.initialize(Reflection.java:66) ~[guava-31.0.1-jre.jar:?]
	at net.bunten.enderscape.Enderscape.onInitialize(Enderscape.java:38) ~[enderscape-0.4.0-1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
	... 7 more

**Comment by lunarbunten** [comment]
Fixed in v0.4.1, please update to the newest version.
